image: dockerfile/nodejs
name: test-example
script:
  - apt-get -y install git make g++ python
  - npm install
  - npm test
env:
  - EXAMPLE_MONGODB_URL=mongodb://$MONGODB_PORT_27017_TCP_ADDR/test-example
services:
  - dockerfile/mongodb
